name: Publish Package to npm

on:
  push:
    tags:
      - "v*.*.*"
jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: corepack & yarn
        run: corepack enable && yarn

      - name: build
        run: yarn build

      # - name: npm release
      #   run: yarn npm publish
      #   env:
      #     NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Package for Github release
        run: |
          mkdir release
          cp -r ./dist ./release/dist
          cp package.json ./release/package.json
          zip -9 -r release.zip ./release/dist
      - name: Github release
        uses: softprops/action-gh-release@v2
        with:
          files: ./
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
